INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 0 ,'', 0 ,'Programmplanung', 0 , null , 2 );
	INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 1 ,'', 1 ,'Abgabe ist vollst�ndig und p�nktlich', 1 , 0 , 5 );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 2 ,'Der rote Faden kann auch kombiniert mit dem "detailierten QP" abgegeben werden.', 2 ,'Ausgeschriebener Roter Faden', 1 , 1 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 3 ,'', 2 ,'QP als Aushang', 1 , 1 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 4 ,'', 2 ,'Grobprogramm des Weekends', 1 , 1 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 5 ,'', 2 ,'Ausgeplante Aktivit�t', 1 , 1 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 6 ,'Auflistung der Aktivit�ten und deren Inhalt. Siehe Cudesch Pfadi Grundlagen.', 2 ,'Detailiertes QP', 1 , 1 , null );
	INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 7 ,'', 1 ,'Kann ein QP Planen', 0 , 0 , 5 );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 8 ,'', 2 ,'Aushang ist vollst�ndig', 1 , 7 , 3 );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 9 ,'', 3 ,'Ort', 1 , 8 , null );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 10 ,'', 3 ,'Zeit', 1 , 8 , null );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 11 ,'', 3 ,'Mitnehmen', 1 , 8 , null );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 12 ,'', 3 ,'Kontakt', 1 , 8 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 13 ,'', 2 ,'5 Aktivit�ten und Weekend sind eingeplant', 1 , 7 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 14 ,'', 2 ,'Roter Faden', 1 , 7 , 2 );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 15 ,'Der Rote Faden kann von uns gelesen werden und wir verstehen was gemeint ist.', 3 ,'Verst�ndlich', 1 , 14 , null );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 16 ,'Ist der Aufwand f�r die Umsetzung verh�ltnissm�sseig oder viel zu gross.', 3 ,'Umsetzbar', 1 , 14 , null );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 17 ,'', 3 ,'Zusammenh�ngend', 1 , 14 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 18 ,'Es muss keine Spannungskurve abgegeben werden. Beim lesen soll die Spannungskurve aber erkenntlich sein.', 2 ,'Spannungskurve �ber das QP ist ersichtlich', 1 , 7 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 19 ,'', 2 ,'QP ist stufengerecht ', 1 , 7 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 20 ,'', 2 ,'QP ist ausgeglichen', 1 , 7 , null );
	INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 21 ,'', 1 ,'Kann eine Aktivit�t planen', 0 , 0 , 6 );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 22 ,'', 2 ,'Aktivit�t mindestens 3h', 1 , 21 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 23 ,'', 2 ,'Zeitaufteilung sinnvoll', 1 , 21 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 24 ,'Der Rote Faden im Block selbst ist gemeint.', 2 ,'Roter Faden', 1 , 21 , 3 );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 25 ,'Der Rote Faden kann von uns gelesen werden und wir verstehen was gemeint ist.', 3 ,'Verst�ndlich', 1 , 24 , null );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 26 ,'Der Rote Faden kann von uns gelesen werden und wir verstehen was gemeint ist.', 3 ,'Umsetzbar', 1 , 24 , null );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 27 ,'', 3 ,'Zusammenh�ngend', 1 , 24 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 28 ,'Es muss keine Spannungskurve abgegeben werden. Beim lesen soll die Spannungskurve aber erkenntlich sein.', 2 ,'Spannungskurve �ber die Aktivit�t ist ersichtlich', 1 , 21 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 29 ,'', 2 ,'Stufengerecht', 1 , 21 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 30 ,'', 2 ,'Ausgeglichen', 1 , 21 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 31 ,'Ist das Programm gen�gend detailiert und verst�ndlich. Kannst du den Block in die Hand nehmen und ihn leiten?', 2 ,'Vollst�ndig ausgeplant', 1 , 21 , null );
	INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 32 ,'', 1 ,'Grobprogramm des Weekends ist verst�ndlich und erkl�rt den zeitlichen Ablauf', 1 , 0 , null );
	INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 33 ,'', 1 ,'AL Gespr�ch', 1 , 0 , 1 );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 34 ,'', 2 ,'Nimmt Inputs entgegen', 1 , 33 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 35 ,'', 2 ,'Reflektiert eigene Planung', 1 , 33 , null );

INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 36 ,'', 0 ,'TNB', 0 , null , 4 );
	INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 37 ,'', 1 ,'TNB Planung', 1 , 36 , 2 );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 38 ,'', 2 ,'P�nktliche Abgabe', 1 , 37 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 39 ,'', 2 ,'Auflagen erf�llt', 1 , 37 , 3 );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 40 ,'', 3 ,'Dauer', 1 , 39 , null );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 41 ,'', 3 ,'Inhaltliche Anforderungen gem�ss Ziel', 1 , 39 , null );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 42 ,'', 3 ,'Material vorhanden', 1 , 39 , null );
	INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 43 ,'', 1 ,'TNLSB Planung', 1 , 36 , 2 );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 44 ,'', 2 ,'P�nktliche Abgabe', 1 , 43 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 45 ,'', 2 ,'Vollst�ndige Abgane', 1 , 43 , 2 );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 46 ,'', 3 ,'Blockvorlage Ausgef�llt', 1 , 45 , null );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 47 ,'', 3 ,'Sicherheits�berlegungen vorhanden', 1 , 45 , null );
	INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 48 ,'', 1 ,'TNLSB J+S Konformit�t', 0 , 36 , 4 );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 49 ,'', 2 ,'Sportlicher Roter Fader erkennbar', 1 , 48 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 50 ,'', 2 ,'Erkennbare dreiteiligkkeit', 1 , 48 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 51 ,'', 2 ,'Sinnvolle Zeiteinteilung', 1 , 48 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 52 ,'', 2 ,'Blockgerechte Sicherheits�berlegungen', 1 , 48 , null );
	INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 53 ,'', 1 ,'TNLSB Pfadikonformit�t', 1 , 36 , 2 );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 54 ,'', 2 ,'Einkleidung stufengerecht', 1 , 53 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 55 ,'', 2 ,'Programm ist stufengerecht', 1 , 53, null );
	INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 56 ,'', 1 ,'Blockleitung', 0 , 36 , 3 );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 57 ,'', 2 ,'Hat eine aktive oder erkl�rende Rolle', 1 , 56 , 1 );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 58 ,'', 3 ,'TNB', 1 , 57 , null );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 59 ,'', 3 ,'TNLSB', 1 , 57 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 60 ,'', 2 ,'TN leitet die Gruppe an', 1 , 56 , 1 );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 61 ,'', 3 ,'TNB', 1 , 60 , null );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 62 ,'', 3 ,'TNLSB', 1 , 60 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 63 ,'Ist sich seiner Rolle als Leiter bewusst.', 2 ,'Tritt als Leitperson auf', 1 , 56 , 1 );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 64 ,'', 3 ,'TNB', 1 , 63 , null );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 65 ,'', 3 ,'TNLSB', 1 , 63 , null );
	INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 66 ,'', 1 ,'TNB Durchf�hrung', 1 , 36 , 1 );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 67 ,'', 2 ,'Setzt die abgegebenen Sicherheits�berlegungen um', 1 , 66 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 68 ,'', 2 ,'Zeitliche Tolleranz von +- 5 Minuten wurde eingehalten.', 1 , 66 , null );
	INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 69 ,'', 1 ,'TNLSB Durchf�hrung', 1 , 36 , 1 );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 70 ,'', 2 ,'Sicherheits�berlegungen umgesetzt', 1 , 69 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 71 ,'', 2 ,'Zeitliche Tolleranz von +- 5 Minuten wurde eingehalten. ', 1 , 69 , null );
	INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 72 ,'', 1 ,'Auswertung', 1 , 36 , 2 );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 73 ,'', 2 ,'Reflektieren ihre Leitung selbstkritisch', 1 , 72 , 1 );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 74 ,'', 3 ,'TNB', 1 , 73 , null );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 75 ,'', 3 ,'TNLSB', 1 , 73 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 76 ,'', 2 ,'K�nnen Kritik annehmen', 1 , 72 , 1 );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 77 ,'', 3 ,'TNB', 1 , 76 , null );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 78 ,'', 3 ,'TNLSB', 1 , 76 , null );

INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 79 ,'', 0 ,'Wanderplanung', 0 , null , 0 );
	INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 80 ,'', 1 ,'Planung', 0 , 79 , 4 );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 81 ,'', 2 ,'Anwanderung 3x3', 1 , 80 , 2 );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 82 ,'', 3 ,'Zeile "Zuhause" ausgef�llt', 1 , 81 , null );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 83 ,'�berlegungen sind Zielf�hrend', 3 ,'Sinnvolle �berlegungen', 1 , 81 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 84 ,'', 2 ,'Unternehmung 3x3', 1 , 80 , 2 );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 85 ,'', 3 ,'Zuhause und vor Ort ausgef�llt', 1 , 84 , null );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 86 ,'�berlegungen sind Zielf�hrend', 3 ,'Sinnvolle �berlegungen', 1 , 84 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 87 ,'', 2 ,'K�nnen eine MZB erstellen', 1 , 80 , 3 );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 88 ,'z.B nicht ein Punkt vor dem Berg und einer danach', 3 ,'Sinnvolle Routenaufteilung', 1 , 87 , null );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 89 ,'', 3 ,'Sinnvolle Geschwindigkeit', 1 , 87 , null );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 90 ,'', 3 ,'Pausen eingeplant', 1 , 87 , null );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 91 ,'', 3 ,'Ortsangaben auf Karte auffindbar', 1 , 87 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 92 ,'', 2 ,'Unterst�tzt die Gruppe bei der Unternehmungsplanung.', 1 , 80 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 93 ,'', 2 ,'K�nnen ein Sicherheitskonzept erstellen', 0 , 80 , 6 );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 94 ,'', 3 ,'Abbruchkriterien erw�hnt und sinnvoll', 1 , 93 , null );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 95 ,'', 3 ,'Alternativrouten / Ausstiegspunkte erw�hnt', 1 , 93 , null );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 96 ,'Umkehrpunkte m�ssen nur erw�hnt sein sofern solche Vorhanden sind. Sollten keine vorhanden sein ist der Punkt als erf�llt zu beurteilen.', 3 ,'Umkehrpunkte erw�hnt', 1 , 93 , null );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 97 ,'', 3 ,'Schl�sselstellen erkannt', 1 , 93 , null );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 98 ,'', 3 ,'Verhaltensregeln �berlegt', 1 , 93 , null );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 99 ,'', 3 ,'Material und Ausr�stung sinnvoll', 1 , 93 , null );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 100 ,'', 3 ,'Verantwortung aufgeteilt', 1 , 93 , null );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 101 ,'', 3 ,'Vorbereitungen auf Handeln im Notfall getroffen.', 1 , 93 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 102 ,'', 2 ,'K�nnen eine sinnvolle Route w�hlen', 1 , 80 , 2 );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 103 ,'Mit stufengerecht ist die Pfadistufe gemeint.', 3 ,'Stufengerechter Schwierigkeitsgrad', 1 , 102 , null );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 104 ,'', 3 ,'Keine unn�tigen Gefahren eingeplant', 1 , 102 , null );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 105 ,'', 3 ,'Geeignete Wege gew�hlt', 1 , 102 , null );
	INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 106 ,'', 1 ,'Durchf�hrung', 0 , 79 , 3 );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 107 ,'', 2 ,'Orientiert sich im Gel�nde', 1 , 106 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 108 ,'', 2 ,'Setzt Pilot Copilot um', 1 , 106 , 1 );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 109 ,'', 3 ,'Spricht sich ab', 1 , 108 , null );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 110 ,'', 3 ,'Sinnvolle Aufgabenteilung', 1 , 108 , null );
			INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 111 ,'', 3 ,'Gegenseitige Unterst�tzung', 1 , 108 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 112 ,'', 2 ,'Leitet die Gruppe auf der Wanderung an', 1 , 106 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 113 ,'', 2 ,'Hat den �berblick �ber die Gruppe', 1 , 106 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 114 ,'', 2 ,'Wendet das 3x3 an', 1 , 106 , null );
	INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 115 ,'', 1 ,'Auswertung', 1 , 79 , 1 );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 116 ,'', 2 ,'Reflektieren ihre Leitung selbstkritisch', 1 , 115 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 117 ,'', 2 ,'K�nnen Kritik annehmen', 1 , 115 , null );

INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 118 ,'', 0 ,'Allgemein', 1 , null , 0 );
	INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 119 ,'', 1 ,'Gibt anderen konstruktive Kritik', 2 , 118 , null );
	INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 120 ,'', 1 ,'Kursregeln einhalten', 0 , 118 , null );
	INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 121 ,'', 1 ,'Ist sich seiner Rolle als Leiter bewusst', 2 , 118 , null );
	INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 122 ,'', 1 ,'TN im Kurs', 2 , 118 , 0 );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 123 ,'', 2 ,'Nimmt aktiv am Programm teil', 2 , 122 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 124 ,'', 2 ,'Zeigt Eigeninitiative', 2 , 122 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 125 ,'', 2 ,'Kann zwischen Ernst und Spass unterscheiden', 2 , 122 , null );
	INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 126 ,'', 1 ,'TN in der Gruppe', 2 , 118 , 0 );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 127 ,'', 2 ,'Respektiert andere', 2 , 126 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 128 ,'', 2 ,'Bringt sich ein', 2 , 126 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 129 ,'', 2 ,'Geht auf andere ein', 2 , 126 , null );
		INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 130 ,'', 2 ,'Kompromissbereitschaft innerhalb der Gruppe', 2 , 126 , null );
	INSERT INTO public.checkbox (id,description,level,name,severity,parent_id,minimumachieved) VALUES ( 131 ,'', 1 ,'Schisst nit ab', 2 , 118 , null );

INSERT INTO benutzer (id,first_name,last_name,username,password,salt) VALUES (0,'Admin','Admin','Admin','$2a$12$x3CPWe7aHiYMLHJvzpjp/eF70/z7jOkdHqUia4WBLAdQQZkMsregK','Cr0b2aRWs2gQ8TG8O6YOb6tXZKiXswCUkyglWaQQOKwYYc1Scn');